PLATFORM_RADON_RELEASE := 1.0
PLATFORM_RADON_VERSION := $(PLATFORM_RADON_RELEASE).$(shell date +%m%d%H%M)

TARGET_PRODUCT_SHORT := $(subst radon_,,$(TARGET_DEVICE))

ifeq ($(TARGET_BUILD_VARIANT),OFFICIAL)
   PLATFORM_RADON_VERSION := $(PLATFORM_RADON_RELEASE)

PROD_VERSION += RadonOS-$(PLATFORM_RADON_RELEASE)-$(TARGET_DEVICE)-$(shell date +%m%d%H%M)-OFFICIAL
else
PLATFORM_RADON_VERSION := $(PLATFORM_RADON_RELEASE)
PROD_VERSION += RadonOS-$(PLATFORM_RADON_RELEASE)-$(TARGET_DEVICE)-$(shell date +%m%d%H%M)-UNOFFICIAL
endif

PRODUCT_PRODUCT_PROPERTIES += \
ro.system.radon.version=$(PLATFORM_RADON_VERSION)
